### ISSUE TITLE
I made a thing

### ISSUE THREAD

**Issue by garyb** [purescript/purescript-gen#1]
@paf31 I made an attempt at something like this years back when QC and SC first split, only I was targeting `Arbitrary` when I did that, which lead to something of a dead end.

My thinking is, if we introduce something like this and have it in core, we can at least provide `MonadGen` constrained functions for generating everything common, and then have implementations of `MonadGen` for QuickCheck, StrongCheck and Jack in each of those libraries.

The operations provided by `MonadGen` itself are pretty basic, so it won't work for some of the fancier tests StrongCheck can do, and there's nothing to help out with shrinking in Jack, but at least we could have a useful set of things that take the pain out of generating test structures that are usable by _everyone_. For all the common stuff there doesn't need to be much in the way of cleverness anyway, that I can think of.

I haven't actually checked the combinators I'm providing in here behave as they should or anything, but just wanted to see if there was any interest in me continuing this, as if it's not in core the utility is somewhat limited.

**Comment by paf31** [comment]
I think it'd be great to have something like this in core. I might have a few comments about the structure (minor ones) if you don't mind, but I think we should work towards getting it added.

**Comment by garyb** [comment]
Yeah certainly!

One of the things with it in its current state is it's relatively light on dependencies, I was trying to make it so we could depend on it mostly everywhere without pulling in too much stuff... so like the `LL` type in here is so we don't need to depend on `-lists`, etc.

Having said that, there are still a good few things pulled in:

- purescript-bifunctors
- purescript-control
- purescript-eff
- purescript-either
- purescript-foldable-traversable
- purescript-globals
- purescript-identity
- purescript-integers
- purescript-invariant
- purescript-math
- purescript-maybe
- purescript-monoid
- purescript-newtype
- purescript-nonempty
- purescript-partial
- purescript-prelude
- purescript-st
- purescript-tailrec
- purescript-tuples
- purescript-unfoldable

But at least it's all very common stuff, and mostly "control"-y rather than data.
