### ISSUE TITLE
Unfoldable leaves Gen state unmodified?

### ISSUE THREAD

**Issue by matthewleon** [purescript/purescript-gen#12]
Apologies for my lack of source code to show this, as I'm encountering it in another project. I'll try to update this issue asap with proof.

In any case, I have a project where I am using the `unfoldable` combinator to craft a generator, and it seems that every time QuickCheck uses that generator, it generates the exact same data.

**Comment by garyb** [comment]
That's more likely to be a bug in the QC instance for `MonadGen`, since the interface here doesn't know about gen state or anything like that... I'm interested to see what's going on with this though!

**Comment by matthewleon** [comment]
Another possibility is that the issue doesn't reside in the `unfoldable` combinator, but rather in QuickCheck's `MonadRec`.

**Comment by matthewleon** [comment]
> That's more likely to be a bug in the QC instance for MonadGen, since the interface here doesn't know about gen state or anything like that... I'm interested to see what's going on with this though!

Yes probably this, rather than `MonadRec`, actually, as each element in the `unfoldable` is indeed different.

**Comment by matthewleon** [comment]
This branch: https://github.com/matthewleon/purescript-sized-vectors/tree/gen

`pulp test` is rigged up to show the output of each iteration.

**Comment by matthewleon** [comment]
It's `resize`, actually :/

Eliminating the `resize` eliminates the problem.

**Comment by garyb** [comment]
Ah, I think I might know what's happening here then. `resize` was "fixed" not too long ago so that it doesn't resize everything _after_ it, only things "inside" it. I guess that part was fixed, but it should still update the seed after it, and now it discards the modified inner state entirely, judging by this.

**Comment by garyb** [comment]
(So it is a bug in QC's instance)

**Comment by safareli** [comment]
🤦‍♂️
