### ISSUE TITLE
Provide `Gen a -> Effect a` function for ease of use.

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/purescript-gen#27]
As mentioned on Slack, provide an easy way to go from `Gen a -> Effect a`. Maybe call it `generate`?

**Comment by garyb** [comment]
There's no `Gen` type in this library, so you can't exactly do that. We could add a `MonadGen` instance for `Effect`, my only reservation about that is `Math.random` isn't exactly a high quality source of randomness, so we'd need to make that clear in the instance documentation. I assume we'd add a dependency on `purescript-random` to implement this too.

**Comment by garyb** [comment]
Actually, from the reading the context of this in Slack, I think the request was to add `Gen ~> Effect` to QuickCheck? `randomSample'` was mentioned, which is a QC thing, as is the `Gen` type.

**Comment by hdgarrood** [comment]
Yes, I think adding it to QuickCheck is what was meant (and I think that does make sense).

**Comment by hdgarrood** [comment]
Would a MonadGen Effect instance be any worse than using Math.random() as a seed for Gen/LCG? Usually the initial seed comes from Math.random() in any case, right?

**Comment by JordanMartinez** [comment]
Ah... Sorry, wrong repo.

**Comment by JordanMartinez** [comment]
Opened it here: purescript/purescript-quickcheck#113

**Comment by garyb** [comment]
> Would a MonadGen Effect instance be any worse than using Math.random() as a seed for Gen/LCG? Usually the initial seed comes from Math.random() in any case, right?

Yeah, and LCG probably isn't all that great either - I was thinking of the case where someone recently was asking about using `genAscii` for some cryptographic thing 🙂
